#!/usr/bin/python3
# -*- coding: utf-8 -*-

from test0 import test
from exams import quiz
import sys

# This should come from a .csv and to have some tags in the dict, and a better variable's name
a = [
	["一","yī","one","Uno","один"],
	["七","qī","seven","Siete","Семь"],
	["三","sān","three","Tres","три"],
	["上","shàng","up","en","вверх"],
	["上午","shàngwǔ","morning","Por la mañana","утро"],
	["下","xià","down","debajo, segundo","вниз"],
	["下午","xiàwǔ","afternoon","por la tarde","после полудня"],
	["下雨","xiàyǔ","rain","lluvia","дождь"],
	["不","bù","no","No (+ verbo)","нет"],
	["不客气","búkèqì","you are welcome","De nada","пожалуйста"],
	["东西","dōngxi","thing, stuff","cosa","вещь, вещи"],
	["个","gè","(classifier for persons)","(clasificador para personas)","(классификатор для лиц)"],
	["中午","zhōngwǔ","noon","mediodía","полдень"],
	["中国","zhōng guó","China","China","Китай"],
	["九","jiǔ","nine","nueve","девять"],
	["书","shū","book","libro","книга"],
	["买","mǎi","buy","comprar","купить"],
	["了","le","(it is used behind a verb or adjective to indicate the end of an action or change)","(Partícula modal para intensificar lo anterior)","(он используется за глаголом или прилагательным для обозначения конца действия или изменения)"],
	["二","èr","two","dos","два"],
	["五","wǔ","five","cinco","пять"],
	["些","xiē","some (quantifier)","algunos (cuantificador)","некоторые (квантификатор)"],
	["人","rén","person","persona","человек"],
	["什么","shénme","what, who","qué, quién","что кто"],
	["今天","jīntiān","today","Hoy, ahora, hoy en día","Cегодня"],
	["他","tā","he, him","él, su","он, он"],
	["他们","tāmen","they (male+female / male, pl.)","ellos","они (мужчина + женщина / мужчина, пл.)"],
	["会","huì","can","poder, ser posible, unión","Можно"],
	["住","zhù","live","vivir","жить"],
	["你","nǐ","you","tú","вы"],
	["你们","nǐmen","you (pl.)","ustedes","ты (пл.)"],
	["做","zuò","do","hacer","делать"],
	["儿子","érzi","son","hijo","сын"],
	["先生","xiānsheng","sir, husband","Señor","сэр, муж"],
	["八","bā","eight","Ocho","восемь"],
	["六","liù","six","seis","шесть"],
	["再见","zàijiàn","good-bye","adiós","Прощай"],
	["写","xiě","write","escribir","записывать"],
	["冷","lěng","cold","frío","холодный"],
	["出租车","chūzūchē","taxi","Taxi","такси"],
	["分钟","fēnzhōng","minute","minuto","минут"],
	["前面","qiánmiàn","in front","en frente","спереди"],
	["北京","běijīng","Beijing","Pekín","Пекин"],
	["医生","yīshēng","doctor","doctor, médico","доктор"],
	["医院","yīyuàn","hospital","hospital","больница"],
	["十","shí","ten","diez","десять"],
	["去","qù","go","ir","идти"],
	["叫","jiào","call","llamar","вызов"],
	["吃","chī","eat","comer","есть"],
	["同学","tóngxué","schoolmate, classmate","compañero de clase","одноклассник, одноклассник"],
	["名字","míngzi","name","nombre de pila","имя"],
	["吗","ma","particle at the end of a question sentence. uh?","¿eh?","частица в конце предложения вопроса. Э? "],
	["听","tīng","listen","escucha","Слушать"],
	["呢","ne","(question particle for subjects already mentioned)","(partícula interrogativa para asuntos antes mencionados)","(частица вопроса для уже упомянутых предметов)"],
	["和","hé","and","y, con","а также"],
	["哪（哪儿）","nǎ (nǎr)","wich, how/where","cuál/dónde","как / где"],
	["商店","shāngdiàn","store","Tienda","хранить"],
	["喂","wèi","hello","Aló","Привет"],
	["喜欢","xǐhuān","love, like","gustar","любить, словно"],
	["喝","hē","drink","beber","напиток"],
	["四","sì","four","cuatro","четыре"],
	["回","huí","return","regreso, vuelta","возвращение"],
	["在","zài","in, at","en","в, в"],
	["坐","zuò","sit","sentarse","сидеть"],
	["块","kuài","piece (quantifier)","Pedazo (cuantificador)","шт (квантификатор)"],
	["多","duō","many, much","mucho, un montón","очень много"],
	["多少","duōshǎo","how many, how much","Cuántos","сколько"],
	["大","dà","big","Grande","большой"],
	["天气","tiānqì","weather","clima","Погода"],
	["太","tài","too (much)","demasiado, también","перебор)"],
	["女儿","nǚér","daughter","hija","дочь"],
	["她","tā","she, her","ella, su","она, ее"],
	["她们","tāmen","they (females, pl.)","ellas","они (женщины, пож.)"],
	["好","hǎo","good, fine","bueno, bien","хорошо хорошо"],
	["妈妈","māma","mother","mamá","мама"],
	["字","zì","character","palabra","персонаж"],
	["学习","xuéxí","study","Aprender","изучение"],
	["学校","xuéxiào","school","colegio","школа"],
	["学生","xuéshēng","student","estudiante","студент"],
	["家","jiā","home","casa","дом"],
	["对不起","duìbùqǐ","I'm sorry","Lo siento","Мне жаль"],
	["小","xiǎo","small","pequeño","маленький"],
	["小姐","xiǎojiě","miss","señorita","скучать"],
	["少","shǎo","few, little","un poco","мало, мало"],
	["岁","suì","year (classifier)","edad (clasificador)","год (классификатор)"],
	["工作","gōngzuò","work","trabajo, empleo","Работа"],
	["年","nián","year","año","год"],
	["开","kāi","open","abierto, abrir","открытый"],
	["很","hěn","quite, very","muy","довольно, очень"],
	["怎么","zěnme","how?, what?, why?","¿cómo? ¿qué? ¿por qué?","как ?, что ?, почему?"],
	["怎么样","zěnmeyàng","how about","que tal","как насчет"],
	["想","xiǎng","want, wish, believe","querer, desear, creer","хочу, хочу, верю"],
	["我","wǒ","I, me","yo","Я, я"],
	["我们","wǒmen","we, us (pl.)","nosotros","мы, мы (пл.)"],
	["打电话","dǎdiànhuà","call up","Telefonear","позвонить"],
	["日","rì","day","día, fecha, sol","день"],
	["时候","shíhou","time","tiempo, hora, periodo","время"],
	["明天","míngtiān","tomorrow","mañana","завтра"],
	["星期","xīngqī","week","semana","неделя"],
	["昨天","zuótiān","yesterday","ayer","вчерашний день"],
	["是","shì","be (am, is, are)","ser, soy, sí","быть (есть, есть, есть)"],
	["月","yuè","month, moon","mes, luna","месяц, луна"],
	["有","yǒu","have","tener, existir","иметь"],
	["朋友","péngyou","friend","amigo","друг"],
	["本","běn","this, roots, origin, source (quantifier)","raíz, origen, éste (cuantificador)","это, корни, происхождение, источник (квантификатор)"],
	["来","lái","come","Llegar","приходить"],
	["杯子","bēizi","cup","taza, vaso","кружка"],
	["桌子","zhuōzi","desk","mesa","стол письменный"],
	["椅子","yǐzi","chair","silla","стул"],
	["水","shuǐ","water","agua","вода"],
	["水果","shuǐguǒ","fruit","Fruta","фрукты"],
	["汉语","hànyǔ","Mandarin Chinese","Chino Mandarín","Китайский мандарин"],
	["没","méi","no","No, no tener","нет"],
	["没关系","méiguānxì","It doesn’t matter, it\s ok.","No importa, está bien","Это не имеет значения, это нормально."],
	["漂亮","piàoliàng","pretty, beaufitul","bonito, precioso","красивая, красивая"],
	["火车站","huǒchēzhàn","train station","estación de tren","железнодорожная станция"],
	["点","diǎn","dot, spot, drop","punto, en punto, gota","точка, точка, капля"],
	["热","rè","hot","calor","жарко"],
	["爱","ài","love","Amor","любовь"],
	["爸爸","bàba","father","padre","отец"],
	["狗","gǒu","dog","perro","собака"],
	["猫","māo","cat","Gato","кошка"],
	["现在","xiànzài","now","ahora mismo","сейчас же"],
	["电影","diànyǐng","movie","película","кино"],
	["电脑","diànnǎo","computer","computadora","компьютер"],
	["电视","diànshì","television","televisión","телевидение"],
	["的","de","of","de","из"],
	["看","kàn","look","Mira","смотреть"],
	["看见","kànjiàn","see","observar","видеть"],
	["睡觉","shuìjiào","sleep","acostarse","спать"],
	["米饭","mǐfàn","rice","arroz cocinado","рис"],
	["老师","lǎoshī","teacher","profesor","учитель"],
	["能","néng","can, be able to","ser capaz de","может, быть в состоянии"],
	["苹果","píngguǒ","apple","manzana","яблоко"],
	["茶","chá","tea","té","чай"],
	["菜","cài","dish, vegetables","plato, verduras","блюдо, овощи"],
	["衣服","yīfu","clothes","ropa","одежда"],
	["认识","rènshi","know","comprensión","знать"],
	["说话","shuōhuà","speak","hablar","разговаривать"],
	["请","qǐng","to ask, to invite, to request","Por favor","просить, приглашать, просить"],
	["读","dú","read, study","Leer, estudiar","читать, учиться"],
	["谁","shéi/shuí","who","quién","ВОЗ"],
	["谢谢","xièxie","thank","Gracias","поблагодарить"],
	["这 (这儿)","zhè ( zhèr)","here, this","Aquí, este","здесь это"],
	["那 (那儿)","nà (nàr)","that/there","alquel/allí","что / есть"],
	["都","dōu","all, each, already","Todo","все, каждый, уже"],
	["里","lǐmiàn","inside","en","внутри"],
	["钱","qián","money","dinero","Деньги"],
	["零","líng","zero","cero","нуль"],
	["飞机","fēijī","airplane","avión","самолет"],
	["饭店","fàndiàn","restaurant","restaurante","ресторан"],
	["高兴","gāoxìng","happy","contento","счастливый"]
]
language = 2  # default: english
if len(sys.argv) > 1:  # some parameters introduced!
	if sys.argv[1] == "--spanish": language = 3
	elif sys.argv[1] == "--russian": language = 4


# Build an array made of dictionaries
dict_array = []

for x in a:
	dict_array.append({
		"chinese":x[0],
		"pinyin":x[1],
		"translation":x[language]#,  # list()
		#"sentences":[],       # list()
		#"tag":""
	})

# TEST-0
#test(dict_array)  # uncomment for test porpouses
quiz(dict_array, language)
